### ISSUE TITLE
[Tokens] Drop some `grid{Min|Maw|}Width*` raw tokens

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/ouds-ios#139]
### Description

Some grid raw tokens are rather web-specific and can be dropped from OUDS iOS.

Here's the reference from OUDS Android that can be removed. We're going to keep only the compact / extra-compact / regular versions of `gridMaxWidth`, `gridMinWidth`, and `gridWidth` (remove the versions with numbers).

```kt
// Android version of raw tokens that have been removed
const val gridMaxWidth100 = 389
const val gridMaxWidth200 = 479
const val gridMaxWidth300 = 735
const val gridMaxWidth400 = 1023
const val gridMaxWidth500 = 1319
const val gridMaxWidth600 = 1639
const val gridMaxWidth650 = 1680
const val gridMaxWidth700 = 1879
const val gridMaxWidth800 = 1920
const val gridMinWidth100 = 1
const val gridMinWidth200 = 390
const val gridMinWidth300 = 480
const val gridMinWidth400 = 736
const val gridMinWidth500 = 1024
const val gridMinWidth600 = 1320
const val gridMinWidth700 = 1640
const val gridMinWidth800 = 1880
const val gridWidth100 = 360
const val gridWidth200 = 390
const val gridWidth300 = 480
const val gridWidth400 = 768
const val gridWidth500 = 1024
const val gridWidth600 = 1440
const val gridWidth700 = 1680
const val gridWidth800 = 1920
```

Reference on OUDS Android side: https://github.com/Orange-OpenSource/ouds-android/blob/db96b330d4df815d802e773f8bfc707894c3c8d0/global-raw-tokens/src/main/java/com/orange/ouds/tokens/global/raw/GridRawTokens.kt#L15

**Comment by pylapp** [comment]
@Tayebsed93 this is your fire baptem :)

What you should do:
- create a branch from this issue
- push it, create an early draft pull request
- remove any tokens mentioned in this issue
- remove / update the tests using them
- look on any documentation if the tokens are used, and replace them
- of course, update the CHANGELOG
