### ISSUE TITLE
[Tooling] Apply everywhere SwiftLint rules for sorted_imports, identifier_name and type_name

### ISSUE THREAD

**Issue by ludovic35** [Orange-OpenSource/ouds-ios#143]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ouds-ios/issues) for duplicate or closed feature requests

### As a

developper

### ... I want to

apply rule for sorted imports and length of variable names.

### ... so that I can

see all import sorted and warn design team of too long tokens names. It seems in demo app the rules are not applied, at least

### Proposed Solution

See:
- https://realm.github.io/SwiftLint/type_name.html
- https://realm.github.io/SwiftLint/identifier_name.html

**Comment by pylapp** [comment]
FYI a bug report has been submitted as I was not able to trigger any warnings fr the `sorted_imports`
https://github.com/realm/SwiftLint/issues/5823

**Comment by pylapp** [comment]
ℹ️ Released with version [v0.4.0](https://github.com/Orange-OpenSource/ouds-ios/releases/tag/0.4.0) 🚀
