### ISSUE TITLE
[Border] - Add borderRadiusPill in border token

### ISSUE THREAD

**Issue by ludovic35** [Orange-OpenSource/ouds-ios#145]
### Description

- Add borderRadiusPill in sementic border token
- Update border page in demo app with this new radius

### Motivation & Context

to have a complete screen in demo app

**Comment by pylapp** [comment]
@ludovic35 No, _borderRadiusPilll_ must not be added. It has been removed since [v0.2.0](https://github.com/Orange-OpenSource/ouds-ios/releases/tag/0.2.0) (https://github.com/Orange-OpenSource/ouds-ios/issues/58).

You should find where this token is used and ask for updates.

Closing this issue.
