### ISSUE TITLE
[Demo App] Add spacing screen 

### ISSUE THREAD

**Issue by ludovic35** [Orange-OpenSource/ouds-ios#149]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ouds-ios/issues) for duplicate or closed feature requests

### As a

a user of the design system for mobile

### ... I want to

see the Spacing (dimension1/2) token

### ... so that I can

approuve the usage of tokens

### Motivation and context

Sub part of issue 
https://github.com/Orange-OpenSource/ouds-ios/issues/120

**Comment by ludovic35** [comment]
modifier la couleur du l(illustration de l'espace quand le token sera disponible
background: var(--color-__decorative-accent-2-default, #4AB4E6);

**Comment by ludovic35** [comment]
Blocked 
- Q1 de we need to illustrâtes all spacings (fixed, gap, ...)
- Q2 do we need to use spacing for horizontal an vertical size class

**Comment by pylapp** [comment]
ℹ️ Released with version [v0.4.0](https://github.com/Orange-OpenSource/ouds-ios/releases/tag/0.4.0) 🚀
