### ISSUE TITLE
[Demo App] Add sizing token screen

### ISSUE THREAD

**Issue by ludovic35** [Orange-OpenSource/ouds-ios#150]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ouds-ios/issues) for duplicate or closed feature requests

### As a

a user of the design system for mobile

### ... I want to

see the Sizing (dimension2/2) token

### ... so that I can

approuve the usage of tokens

**Comment by pylapp** [comment]
ℹ️ Released with version [v0.4.0](https://github.com/Orange-OpenSource/ouds-ios/releases/tag/0.4.0) 🚀
