### ISSUE TITLE
[Demo App] Add Colors token screen

### ISSUE THREAD

**Issue by ludovic35** [Orange-OpenSource/ouds-ios#152]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ouds-ios/issues) for duplicate or closed feature requests

### As a

a user of the design system for mobile

### ... I want to

see the Color token

### ... so that I can

understand the colors that are available for me to use

### Proposed Solution

The colors to be displayed are the Semantic colors tokens except for the alias or brand tokens

### Other

The DSM pages of the color token reflects what colors should be used:
https://unified-design-system.orange.com/472794e18/p/217ac6-colour/b/697d3b

**Comment by pylapp** [comment]
ℹ️ Released with version [v0.4.0](https://github.com/Orange-OpenSource/ouds-ios/releases/tag/0.4.0) 🚀
