### ISSUE TITLE
[Demo App] On opacity screen, add a border around the view showing the opacity

### ISSUE THREAD

**Issue by ludovic35** [Orange-OpenSource/ouds-ios#157]
### Prerequisites

- [x] I have [searched the backlog](https://github.com/Orange-OpenSource/ouds-ios/issues) for duplicate or closed feature requests

### As a

demo app tester

### ... I want to

have a border arrond the view showing the opacity 

### ... so that I can

the transparent effect when there is no opacity

**Comment by pylapp** [comment]
ℹ️ Released with version [v0.4.0](https://github.com/Orange-OpenSource/ouds-ios/releases/tag/0.4.0) 🚀
