### ISSUE TITLE
[Tokens] Raw brand-specific color tokens renaming

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/ouds-ios#179]
### Description

Raw color tokens, common or specific to a brand, should have the same prefix in the library. They will be generated this way by the parser that will handle design tokens.

So this issue means that each and every `colorBrand*` **raw token** should be named "color*" instead:
- `colorBrandOrange{100 to 900}` → `colorOrange{100 to 900}`
- `colorBrandWarmGray{100 to 900}` → `colorWarmGray{100 to 900}`

**Comment by pylapp** [comment]
ℹ️ Released with version [v0.4.0](https://github.com/Orange-OpenSource/ouds-ios/releases/tag/0.4.0) 🚀
