### ISSUE TITLE
[DemoApp]: Fix some design isssues

### ISSUE THREAD

**Issue by ludovic35** [Orange-OpenSource/ouds-ios#189]
### Prerequisites

- [x] I have [searched the backlog](https://github.com/Orange-OpenSource/ouds-ios/issues) for duplicate or closed feature requests

### As a

user of the demo application

### ... I want to

the same presentation of all token illustrations

### ... so that I can

see all token easily

### Motivation and context

1. Use same typo on description (.typeBodyDefaultLarge(theme) on all screens
2. Use same typo on token name (.typeBodyStrongLarge(theme) on token illustration  (exemple "elevationNone" on the elevation screen)
3. Use same typo on token value .typeBodyDefaultMedium(theme) on token illustration (exemple "x: y: .." on the elevation screen)
4. Try toi add unit og the token (exemple border)
5. Try to mutualise the illustration view (refactring)

**Comment by pylapp** [comment]
ℹ️ Released with version [v0.4.0](https://github.com/Orange-OpenSource/ouds-ios/releases/tag/0.4.0) 🚀
