### ISSUE TITLE
[DemoApp] Update opacity screen

### ISSUE THREAD

**Issue by ludovic35** [Orange-OpenSource/ouds-ios#200]
### Prerequisites

- [x] I have [searched the backlog](https://github.com/Orange-OpenSource/ouds-ios/issues) for duplicate or closed feature requests

### As a

designer valider

### ... I want to

see the opacity well illustration

### ... so that I can

to validate all tokens

### Motivation and context

1. Add border on a rectangle illustrates opacity for all tokens
2. Add bleu color on "checkerboard"

**Comment by pylapp** [comment]
ℹ️ Released with version [v0.4.0](https://github.com/Orange-OpenSource/ouds-ios/releases/tag/0.4.0) 🚀
