### ISSUE TITLE
[Token Update] Border semantic token update

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/ouds-ios#207]
### Type of tokens

- [ ] Raw token (i.e. associated to _SwiftUI_ or _Swift_ value)
- [x] Semantic token (i.e. pointing to a raw token)
- [ ] Component token (i.e. pointing to a semantic token, used for a component)

### Description

Some changes regarding the border semantic tokens:
* `borderWidthOutsideFocus` is renamed `borderWidthFocus`
* `borderWidthFocusInset` is new and has `borderWidth75` as value

```diff
public static let borderStyleDefault = borderStyleSolid
public static let borderStyleDrag = borderStyleDashed
public static let borderWidthDefault = borderWidth25
+ public static let borderWidthFocus = borderWidth50
+ public static let borderWidthFocusInset = borderWidth75
public static let borderWidthMedium = borderWidth50
public static let borderWidthNone = borderWidth0
- public static let borderWidthOutsideFocus = borderWidth50
public static let borderWidthThick = borderWidth75
public static let borderWidthThicker = borderWidth100
```

### Motivation & Context

-

### Types of change

- [x] Add new tokens
- [x] Update existing tokens (i.e. change name or value)
- [x] Remove existing token

### Checklist for Core Team

- [ ] Tokens have been updated
- [ ] Documentations have been updated
- [ ] Unit tests have been updated
- [ ] Retrocompatibility has been checked, or broken API have been flagged as deprecated with a workaround

**Comment by pylapp** [comment]
@Tayebsed93 Il va falloir probablement que tu mettes à jour ta branche pour l'issue #154 afin d'ajouter les tests unitaires qui testent `borderWidthFocusInset` en prenant en compte ce renommage de `borderWidthOutsideFocus` en `borderWidthFocus`
