### ISSUE TITLE
[Token Update] Elevation semantic token update

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/ouds-ios#209]
### Type of tokens

- [ ] Raw token (i.e. associated to _SwiftUI_ or _Swift_ value)
- [x] Semantic token (i.e. pointing to a raw token)
- [ ] Component token (i.e. pointing to a semantic token, used for a component)

### Description

Some elevation semantic tokens have been removed:
- `elevationBlurFocus`
- `elevationXFocus`
- `elevationYFocus`
- `elevationColorFocus`

It also means that you can drop the composite `elevationFocus` token, or any `elevation*Focus` tokens.

### Motivation & Context

-

### Types of change

- [ ] Add new tokens
- [ ] Update existing tokens (i.e. change name or value)
- [x] Remove existing token

### Checklist for Core Team

- [x] Tokens have been updated
- [x] Documentations have been updated
- [x] Unit tests have been updated
- [x] Retrocompatibility has been checked, or broken API have been flagged as deprecated with a workaround

**Comment by julien-deramond** [comment]
Put a "blocking" label on this one. Please wait until I sync something weird with the designers.

**Comment by julien-deramond** [comment]
Issue unblocked, the description is updated regarding the "elevation-focus" token.

**Comment by pylapp** [comment]
@Tayebsed93 Pour l'issue #154 il faudra si besoin que tu prennes en compte que ces tokens ont été retirés
