### ISSUE TITLE
[Bug] app crash on color token page opening

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ouds-ios#215]
### Prerequisites

- [x] I have [searched the backlog](https://github.com/Orange-OpenSource/ouds-ios/issues) for duplicate or closed feature requests

### Your test device

iPhone 14 Pro

### OS Version

17.6.1

### App version

V0.4.0 1729285509

### App orientation

Portrait

### Device language

US

### App language

EN

### Describe the issue

The app crashed when I opened the color token page

### Expected Behavior

Not to crash obviously ;)

### Accessibility settings

None

**Comment by pylapp** [comment]
Maybe this is because a color semantic token has not been implemented due to the fact the design system has holes in their definitions. The token must be found and not integrated in the demo app.

That is an issue for @ludovic35

**Comment by pylapp** [comment]
See https://github.com/Orange-OpenSource/ouds-ios/issues/216
