### ISSUE TITLE
Content on background colors displayed twice

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ouds-ios#236]
### Prerequisites

- [x] I have [searched the backlog](https://github.com/Orange-OpenSource/ouds-ios/issues) for duplicate or closed feature requests

### Your test device

NA

### OS Version

NA

### App version

Alpha 0.5.0 - git 201

### Describe the issue

The color token page displays the « Content on background » 2x

### Expected Behavior

Showcit only once

### Accessibility settings

Na

**Comment by pylapp** [comment]
@B3nz01d I do not understand what "Alpha 0.5.0 - git 201" means.
For text bugs to will have to bring more details.
I will upload the issue template to let user refer the build details.

**Comment by B3nz01d** [comment]
It's the reference in the about page - I cannot open it as it was already updated with another version of the app.

**Comment by pylapp** [comment]
We don't refer to "git 201", it doe snot match anything. And _TestFlight_ allows to onstlal previous builds.
BTW the bug has been spotted and the fix is under review.
