### ISSUE TITLE
[Token Update] `sizeTypeMaxWidth*` -> `sizeMaxWidthType*` renaming

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/ouds-ios#243]
### Type of tokens

- [ ] Raw token (i.e. associated to _SwiftUI_ or _Swift_ value)
- [x] Semantic token (i.e. pointing to a raw token)
- [ ] Component token (i.e. pointing to a semantic token, used for a component)

### Description

On October 22-24, `sizeTypeMaxWidth*` semantic tokens have all been renamed to `sizeMaxWidthType*` (e.g. `sizeTypeMaxWidthBodyLargeDesktop` → sizeMaxWidthTypeBodyLargeDesktop)

### Motivation & Context

-

### Types of change

- [ ] Add new tokens
- [x] Update existing tokens (i.e. change name or value)
- [ ] Remove existing token

### Checklist for Core Team

- [ ] Tokens have been updated
- [ ] Documentations have been updated
- [ ] Unit tests have been updated
- [ ] Retrocompatibility has been checked, or broken API have been flagged as deprecated with a workaround

**Comment by pylapp** [comment]
@julien-deramond FYI it was already the cas ein our iOS codebase ; we only manage tokens with the format like *sizeMaxWidthType*.
Closing this issue has already done :)
