### ISSUE TITLE
[Bug] [Demo App] A11y Dynamic Type Text

### ISSUE THREAD

**Issue by Tayebsed93** [Orange-OpenSource/ouds-ios#247]
### Prerequisites

- [x] I have [searched the backlog](https://github.com/Orange-OpenSource/ouds-ios/issues) for duplicate or closed feature requests

### Your test device

iPhone 14 pro Max

### OS Version

iOS 17.5.1

### App version

0.5.0

### App build number

13

### App build type

DEBUG

### App orientation

Portrait

### Device language

French

### App language

English

### Describe the issue

On iOS, when text is enlarged to 235%, "standard" size text must scale according to the native settings. The content must be displayed without any loss of information or functionality (e.g., no truncated, hidden, or overlapping content) and without requiring scrolling in both directions (horizontal and vertical).

![Image](https://github.com/user-attachments/assets/d6e63327-a8cf-4804-a212-a83083a3f0d4)

### Expected Behavior

The text must enlarge accordingly 

### Accessibility settings

Increased text sizes (DynamicType)

**Comment by pylapp** [comment]
@Tayebsed93 @ludovic35 Est-ce que vous pouvez m'expliquer la nomenclature utilisée dans ce message de commit ainsi que celle du CHANGELOG ?! Ça ne respecte pas du tout la nomenclature *conventional commit messages*, pourtant c'est documenté *a minima* dans le fichier DEVELOP ! Idem pour les bonnes pratiques *keep à CHANGELOG*.

Ce message de commit est totalement à refaire : il manque l'action, le titre ne veut rien dire, et ensuite il message la référence à l'issue ou la PR. J'espère au moins que vous avez bien fait un merge en faisant un squash et un commit de merge !

C'est dommage de constater que,
si je m'absente deux jours, des choses simples comme ça ne sont pas appliquées alors qu'on en a déjà discuté et que c'est trivial.

Il me paraît nécessaire que l'on se fasse confiance en travaillant tous de la même façon, notamment en appliquant ces bonnes pratiques.

Un bon message de commit aurait été : 

fix(a11y): dynamic type text for view XXX (#247) (253)

Où XXX est la vue modifiée.

Concernant le CHANGELOG, la ligne doit être dans une section "Fixed", en retirant le mot clé "[Bug]" ne servant à rien, en utilisant "[DemoApp]" plutôt que "[Demo App]" et avec un texte utile.

Je ne comprends pas comme ça a pu être mergé ; peut-être que c'est le rendu de l'app GitHub qui m'induit en erreur.

Si je n'oublie pas d'ici là je procéderais à une réécriture de l'historique Git ; en l'état vous ne pouvez pas le faire car un _ruleset_ empêche les _force push_ sur la branche _develop_ et comme vous n'êtes pas administrateurs du dépôt vous ne pouvez désactiver cette règle.

Faîtes attention la prochaine fois svp. On se doit d'entre rigoureux surtout au début du projet !

**Comment by pylapp** [comment]
@Tayebsed93 @ludovic35 Pourquoi dans le code d'une fonction je vois des commentaires DocC caractérisés par trois slash ?

Et c'est quoi ce code mis en commentaire sans explication ?

Il va falloir que l'on soit plus rigoureux sur les revues de code, quitte à imposer au moins deux relecteurs tant qu'on est trois sur le projet au moins.
