### ISSUE TITLE
[DemoApp] Update space token screen

### ISSUE THREAD

**Issue by ludovic35** [Orange-OpenSource/ouds-ios#275]
### Prerequisites

- [x] I have [searched the backlog](https://github.com/Orange-OpenSource/ouds-ios/issues) for duplicate or closed feature requests

### As a

Developer

### ... I want to

illustrate all tokens

### ... so that I can

see the result

### Motivation and context

* On space screen : add missing tokens
* On space screen: add illustration with text for all sections in screen

**Comment by B3nz01d** [comment]
@ludovic35 where can I test this, I do not see any Alpha version associated to this issue?
