### ISSUE TITLE
Common cross-libraries token architecture

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/ouds-ios#33]
### Description

This issue aims to define and implement a common cross-libraries token architecture for the tech libraries: Android, iOS, Flutter, and web.

Design tokens are defined on the design side via Figma, and Figma's capability to handle and define tokens is more limited compared to what we can do on the development side. So there will be a slight discrepancy between the design and the tech side.

In essence, Figma’s token mechanism requires designers to pre-create a set of tokens that may not be inherently useful for the core part of our tech libraries.

On the technical side, it is important to define what is available by default:
* for developers using the Orange theme (default)
* what can be overridden for country-specific themes, and how overrides will function for B-Brand themes

This must be considered at different levels of the token stack, including primitive raw values, semantic tokens, and component tokens.

Our objective is to establish a common cross-library architecture to ensure uniformity in terminology and implementation.

> [!NOTE]  
> Closing this issue will unlock all the "Tokens: *" issues in this repository

> [!IMPORTANT]  
> The possibility to add semantic tokens from outside is a topic we'd like to deep dive in. However, creating prototypes for that now, is considered as too complex as we don't have yet libraries handling tokens. The safest approach is to limit the scope of this study.

Based on the study done on the Android side in https://github.com/Orange-OpenSource/ouds-android/issues/34, in terms of customization, our libraries will need to handle first only a light customization such as white-label themes.

Said differently, our libraries will define only the raw/semantics/components tokens needed for the global core Orange theme. And only these tokens would be updatable. It also means that our tech libraries won't contain at first the concepts coming from B-Brands that are not used in the core library. Basically, it's like what has been done in ODS, but with a new constraint: the theme should be extendable.
An extended theme can rewire semantic tokens with its own raw tokens and component tokens with semantic tokens. It defines its own raw tokens (often generated from Figma) and doesn't need to access the raw tokens of the parent theme.

It corresponds to the schema presented in the "Android architecture" section in https://github.com/Orange-OpenSource/ouds-android/issues/34.

#### Implementation

As a summary, for the implementation part:

- [x] Implement the architecture defined in the "Technical details" section
- [x] Create a fake component in order to test the usage
- [x] Check that the documentation and the demo app can access the semantic and components tokens
- [x] Create a mock library using OUDS iOS to customize the dummy component for a light-themed environment, like a white-label library.
- [x] Create a theme extending the Orange theme which has its own raw tokens and can rewire Orange semantics and/or components tokens

### Study

- [x] Study the limitations and the way it could be done on iOS

##### Main goals

The technical architecture must tackle several topics like the user experience, the developer experience, the ecodesign principles and also the source code maintanability and efficiency. We should also keep in mind a lof of tokens will be added in the code base (hundreds or thousands) and plenty of them must be overridable, so the library must be robust, tested and scalable.

##### Architecture of the Swift Package

First, the OUDS iOS library, as a _Swift Package_ should expose fine grained products with their own responsibilities, e.g. several modules for: raw tokens, semantic tokens, components takes, shared elements for themes, Orange theme, comonents, modules and foundations. Thus developers using the OUDS iOS library will be able to pull in _Xcode_ the modules they want and keep their code base clean. Having several modules will help to test the codebase and keep things clean by splitted repsonsabilites and reducing the frictions between all the parts of the library.

The module dedicated to OUDS _modules_ must rely on the OUDS _components_. Theses _components_ laod their style using _component tokens_ and the _Orange theme_ as a default theme. The _Orange theme_ is based on _shared elements_ mainly defining what a theme is. Any _semantic tokens_ and _raw tokens_ are also used by _themes_.

<img width="918" alt="OUDS - iOS - Chart - Package diagram (v2)" src="https://github.com/user-attachments/assets/28a4a6ab-aba2-46a9-8818-358c2bf0973f">

##### Architecture of themes

The _object oriented_ paradigme implementation in Swift is a bit different that the one found with Java or Kotlin. For example we do not have _abstract classes_ and Swift relies a lot in composition with _protocols_ and _extensions_. Thus a theme can be composed using protocols containing as properties the _semantics tokens_. These tokens must also be overridable. Any defailt values and logic can be in a kind of fake abstract class named `OUDSTheme`. This theme will be then subclassed using OOP inheritance in the real default theme named `OrangeTheme`. Any other theme can be a subclass of `OrangeTheme` (e.g. country specific theme) or `OUDSTheme` (for white label).

Themes must be able to override _semantic tokens_ and _components tokens_, and use its own _raw tokens_ without sharing them to other themes. The exiting _raw tokens_, shared between all themes, are not overridable because their definitions are frozen.

<img width="1098" alt="OUDS - iOS - Chart - Themes classes diagram (v2)" src="https://github.com/user-attachments/assets/7ecc6f06-a6e9-4099-b640-972728ddd9de">

##### Architecture of components tokens

_Components tokens_ can be defined so as to be used in components and make the glue with _semantic tokens_. They mus tbe overridable by themes.

##### Architecture of semantic tokens

_Semantic tokens_ are used by _components tokens_ and _shared definition of themes_. They are spltited in kind of families, i.e. borders, dimensions, colors, spacings, elevations, sizings, opacities, grids and typographies. For some of theses tokens, like for borders, subfamilies can be defined likes width, radius and style. Finally, any of these raw tokens is associated to a raw value which will be - in the end - applied to _SwiftUI views_ inside _components_. Type aliases will help to make a simple math between any _semantic tokens_ and _raw tokens_.

<img width="2592" alt="OUDS - iOS - Chart - Semantic token classes diagram (v2)" src="https://github.com/user-attachments/assets/4feb2e24-e184-4dce-b3dd-87c61275774d">

##### Architecture of raw tokens

To avoid to define data structures which can be heavy in the end like _class_ or _structs_, only primitives types are used for _raw tokens_ (thus indirectyl for higher level tokens like _semantics_ and _components_ ones). Use each time type aliases whill help develoeprs to find easily which type of tokens they want without using bigger objects.

<img width="1530" alt="OUDS - iOS - Chart - Raw token classes diagram (v2)" src="https://github.com/user-attachments/assets/ee5b42b4-55f4-4665-b8f5-14b66a335eb4">

**Comment by pylapp** [comment]
@julien-deramond Pour ne pas polluer la définition de cette carte, je mets ci-dessous pour traçabilité mes commentaires :)

D'une part, j'ai modifié ce ticket en décrivant l'architecture du _Swift package_ *OUDS iOS*, y apportant notamment des schémas en reprenant des notions UML.
J'ai pu également testé le passage à l'échelle de notre architecture en générant, via un script Shell, les lignes de codes Swift pour définir l'ensemble des _raw tokens_ et _semantic tokens_ que l'on peut trouver dans l'outil de whieboard de l'équipe de design. Cela a permis finalement de concevoir quelques choses de souple.
À voir toutefois dans la durée ce que ça donnera : entre la génération de tokens en Swift via un JSON exporté avec [style-dictionary](https://github.com/amzn/style-dictionary), le besoin d'avoir tout surchargeable, et la quantité astronomique de tokens, conjugués avec le besoin d'avoir une base de code propre, testable, facilement utilisable et pas lourde pour les utilisateurs, peut-être devrons-nous faire face à des soucis structurels. Mais pour l'instant, la version actuelle sur la branche **33-define-tokens-architecture** comporte 1 059 tokens (_components_, _semantics_ et _raws_ confondus géénrés en 25 secondes) et ça tient la route.

Il est possible de définir un thème "complet" en surchargeant chacun de ces tokens et en étant assez masochiste.

Sinon, le thème de base est le "thème Orange" embarquant ses propres _raw tokens_ de couleurs et surchargeant certains _semantic tokens_. Ce thème peut être dérivé aussi. 

L'architecture actuelle de manière générale va définir un thème "abstrait" qui aura des valeurs par défauts ; ici naïvement en reprenant un à un toutes les définitions des tokens du tableau blanc de l'équipe de design. Le thème "Orange" est basé sur ce thème "abstrait" mais séparé afin qu'il embarque ses propres raws tokens sans les exposer dehors.

J'ai pu faire une app à part pour embarquer la lib OUDS iOS et définir un thème basé sur celui Orange, tout est bon.

L'app de démo du projet OUDS iOS comporte un composant banal (vaguement inspiré du composant *forms input text* du tableau blanc), auquel on applique le thème Orange ou un thème "local" (défini en dehors de la lib iOS OUDS).

Bref, la version sur cette branche de la lib iOS permet de répondre aux besoins suivis : 
- définir son propre thème
- surcharger un thème existant
- définir de manière exclusive des _raw tokens_ pour un thème donné (ça devrait être bon aussi pour les _semantics_ et les _components_)
- laisser la possibilité de surcharger / redéfinir des _semantics tokens_ et _components tokens_
- gérer plusieurs centaines de tokens exposés au travers du thème
- être simple à utiliser au travers de la manipulation du thème

Restera, pour d'autres jalons, à creuser la génération de la documentation avec DooC pour Swift comme vu par @ludovic35  et aussi les tests unitaires. En effet, même si à terme les tokens seront générés, on peut faire la supposition que les variables auront une immense majorité du temps les mêmes noms mais pas les mêmes valeurs. Pour certains _raw tokens_ on peut tester les relations d'ordre (un `fontSize100` devant être plus petit qu'un `fontSize200` par exemple). On peut aussi vérifier que les tokens sont bien surchargeables entre un thème dérivé et son thème parent. Ainsi, avoir des tests unitaires câblés sur la chaîne de CI/CD pourra nous assurer que le code Swift généré et intégré n'apporte pas des régressions de ce genre. À investiguer.

[UML charts, tokens generation Shell script.zip](https://github.com/user-attachments/files/16472170/UML.charts.tokens.generation.Shell.script.zip)

**Comment by pylapp** [comment]
Ci joints, une vidéo de l'app de démo avec une bascule de thème (Orange / quelconque) et un changement de mode (clair / sombre), ainsi qu'une capture d'écran de l'app banale "Hello world" avec ses propres thème et _raw tokens_ appliqués au même composant exposé via la lib OUDS iOS.

![Hello world app](https://github.com/user-attachments/assets/b6353ff4-dbe0-469d-970f-d0a4a270beb6)
https://github.com/user-attachments/assets/15320207-37db-48dc-88f7-0d7f386f3277

**Comment by pylapp** [comment]
You can find the sample component with basic themes in the last TestFlight alpha version upload:

- Version: **0.0.0**
- Build number: **1722613341**
- Build type: **ALPHA (93ae267)**
- Build details (GitHub): **33**

**Comment by pylapp** [comment]
May be linked with https://github.com/Orange-OpenSource/ouds-ios/issues/5

**Comment by pylapp** [comment]
FYI this issue can be seen as "delviered" since version [v0.0.0](https://github.com/Orange-OpenSource/ouds-ios/releases/tag/0.0.0) even if the architecture might evolve a bit in the future (see #79)
