### ISSUE TITLE
[Bug]: Fix issues in privacy policy file

### ISSUE THREAD

**Issue by ludovic35** [Orange-OpenSource/ouds-ios#42]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ouds-ios/issues) for duplicate or closed feature requests

### Your test device

ALL

### OS Version

ALL

### App version

ALL

### App orientation

ALL

### Device language

ALL

### App language

ALL

### Describe the issue

Update Name

### Expected Behavior

Update Name

### Accessibility settings

Update Name

**Comment by ludovic35** [comment]
Oups the file is good. Test has made on an old version of app

**Comment by pylapp** [comment]
Ok, closing this issue so.
