### ISSUE TITLE
Create the basic architecture of the library

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/ouds-ios#5]
### Description

Let's create the basic architecture of the library.

- [ ] xxx
- [ ] Add an "In Library" header in the THIRD-PARTY.md (as done in https://raw.githubusercontent.com/Orange-OpenSource/ods-ios/qualif/THIRD-PARTY.md), and the first elements used in this library
- [ ] If any images are used, please fill the NOTICE.txt file

**Comment by pylapp** [comment]
Closes as implemented in #33
