### ISSUE TITLE
[Demo App] Guidelines

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/ouds-ios#54]
### Description

This issue defines how to render guidelines in the demo application.

> [!NOTE]  
> TODO: define precisely the content of this feature. This issue was created to store and not forget the technical constraint that was decided during the common cross-libraries tokens architecture study.

#### Constraints

- On the development side, the data structure of the tokens should not be modified or made more complex to display features like colors in the demo app, as was done for ODS. Instead, this complexity should be managed within the documentation and/or the demo app directly, rather than within the library.

**Comment by pylapp** [comment]
Maybe a good first issue for @ludovic35 when he will be back

**Comment by julien-deramond** [comment]
FYI, I'm not sure the content of the demo apps have been defined yet by the designers. It'll be probably really close to the ODS one, but let's clarify the specs before starting developing this issue.

**Comment by pylapp** [comment]
Ok, so add *blocking* label while we don't have specifications ; it will help to find ready to implement issues.

**Comment by pylapp** [comment]
Finaly got resources, designers and guidelines in *Figma*, closing this issue, not relevant anymore.
